// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ZBP
{
    public partial class WigPrediction
    {
        /// <summary>
        /// model input class for WigPrediction.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Date")]
            public DateTime Date { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"Wig")]
            public float Wig { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"Wig20")]
            public float Wig20 { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"PlnChfRate")]
            public float PlnChfRate { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"PlnEurRate")]
            public float PlnEurRate { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"PlnGbpRate")]
            public float PlnGbpRate { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"PlnUsdRate")]
            public float PlnUsdRate { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"CpiChf")]
            public float CpiChf { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"CpiGbp")]
            public float CpiGbp { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"CpiPln")]
            public float CpiPln { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"CpiUsd")]
            public float CpiUsd { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"CpiEur")]
            public float CpiEur { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"InterestRatePln")]
            public float InterestRatePln { get; set; }

            [LoadColumn(13)]
            [ColumnName(@"PublicDebtPL")]
            public float PublicDebtPL { get; set; }

            [LoadColumn(14)]
            [ColumnName(@"POL_DebtPerGDP")]
            public float POL_DebtPerGDP { get; set; }

            [LoadColumn(15)]
            [ColumnName(@"POL_PopulationGrowth")]
            public float POL_PopulationGrowth { get; set; }

            [LoadColumn(16)]
            [ColumnName(@"POL_Unemployment")]
            public float POL_Unemployment { get; set; }

            [LoadColumn(17)]
            [ColumnName(@"POL_GDP_Growth")]
            public float POL_GDP_Growth { get; set; }

            [LoadColumn(18)]
            [ColumnName(@"POL_GDP")]
            public float POL_GDP { get; set; }

            [LoadColumn(19)]
            [ColumnName(@"POL_GDP_PC")]
            public float POL_GDP_PC { get; set; }

            [LoadColumn(20)]
            [ColumnName(@"POL_GDP_PPP")]
            public float POL_GDP_PPP { get; set; }

            [LoadColumn(21)]
            [ColumnName(@"POL_GDP_PPP_PC")]
            public float POL_GDP_PPP_PC { get; set; }

            [LoadColumn(22)]
            [ColumnName(@"EU_GDP_Growth")]
            public float EU_GDP_Growth { get; set; }

            [LoadColumn(23)]
            [ColumnName(@"EU_GDP")]
            public float EU_GDP { get; set; }

            [LoadColumn(24)]
            [ColumnName(@"EU_GDP_PC")]
            public float EU_GDP_PC { get; set; }

            [LoadColumn(25)]
            [ColumnName(@"EU_GDP_PPP")]
            public float EU_GDP_PPP { get; set; }

            [LoadColumn(26)]
            [ColumnName(@"EU_GDP_PPP_PC")]
            public float EU_GDP_PPP_PC { get; set; }

            [LoadColumn(27)]
            [ColumnName(@"Lse")]
            public float Lse { get; set; }

            [LoadColumn(28)]
            [ColumnName(@"Nasdaq")]
            public float Nasdaq { get; set; }

            [LoadColumn(29)]
            [ColumnName(@"Nyse")]
            public float Nyse { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for WigPrediction.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Date")]
            public DateTime Date { get; set; }

            [ColumnName(@"Wig")]
            public float Wig { get; set; }

            [ColumnName(@"Wig20")]
            public float Wig20 { get; set; }

            [ColumnName(@"PlnChfRate")]
            public float PlnChfRate { get; set; }

            [ColumnName(@"PlnEurRate")]
            public float PlnEurRate { get; set; }

            [ColumnName(@"PlnGbpRate")]
            public float PlnGbpRate { get; set; }

            [ColumnName(@"PlnUsdRate")]
            public float PlnUsdRate { get; set; }

            [ColumnName(@"CpiChf")]
            public float CpiChf { get; set; }

            [ColumnName(@"CpiGbp")]
            public float CpiGbp { get; set; }

            [ColumnName(@"CpiPln")]
            public float CpiPln { get; set; }

            [ColumnName(@"CpiUsd")]
            public float CpiUsd { get; set; }

            [ColumnName(@"CpiEur")]
            public float CpiEur { get; set; }

            [ColumnName(@"InterestRatePln")]
            public float InterestRatePln { get; set; }

            [ColumnName(@"PublicDebtPL")]
            public float PublicDebtPL { get; set; }

            [ColumnName(@"POL_DebtPerGDP")]
            public float POL_DebtPerGDP { get; set; }

            [ColumnName(@"POL_PopulationGrowth")]
            public float POL_PopulationGrowth { get; set; }

            [ColumnName(@"POL_Unemployment")]
            public float POL_Unemployment { get; set; }

            [ColumnName(@"POL_GDP_Growth")]
            public float POL_GDP_Growth { get; set; }

            [ColumnName(@"POL_GDP")]
            public float POL_GDP { get; set; }

            [ColumnName(@"POL_GDP_PC")]
            public float POL_GDP_PC { get; set; }

            [ColumnName(@"POL_GDP_PPP")]
            public float POL_GDP_PPP { get; set; }

            [ColumnName(@"POL_GDP_PPP_PC")]
            public float POL_GDP_PPP_PC { get; set; }

            [ColumnName(@"EU_GDP_Growth")]
            public float EU_GDP_Growth { get; set; }

            [ColumnName(@"EU_GDP")]
            public float EU_GDP { get; set; }

            [ColumnName(@"EU_GDP_PC")]
            public float EU_GDP_PC { get; set; }

            [ColumnName(@"EU_GDP_PPP")]
            public float EU_GDP_PPP { get; set; }

            [ColumnName(@"EU_GDP_PPP_PC")]
            public float EU_GDP_PPP_PC { get; set; }

            [ColumnName(@"Lse")]
            public float Lse { get; set; }

            [ColumnName(@"Nasdaq")]
            public float Nasdaq { get; set; }

            [ColumnName(@"Nyse")]
            public float Nyse { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("WigPrediction.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
